import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SparkleIcon from "./components/SparkleIcon.js";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-[#9747FF] to-[#7D4BFF] min-h-screen text-white`}>
        <main className="p-4 mt-2 mx-10">
           <header className="flex justify-between mb-3">
        <Link href="/" className="flex ">
          <SparkleIcon/>
          Epic Captions</Link>
        <div className="flex gap-4">
          <Link href="">Home</Link>
          <Link href="/pricing">Pricing</Link>
          <Link href="mailto:contact@epiccaption.com">Contact</Link>
        </div>
      </header>
        {children}
       </main>
      </body>
    </html>
  );
}
